services:
  mongo:
    image: mongo
    container_name: mongoContainer
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongo:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  postgresqlOrder:
    image: postgres
    container_name: postgres-containerOrder
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  postgresqlInventory:
    image: postgres
    container_name: postgres-containerInve
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory
    volumes:
      - postgresInventory:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  mongo:
  postgres:
  postgresInventory: